### ISSUE TITLE
Manca Petaloso

### ISSUE THREAD

**Issue by KarlFiabeschi** [napolux/paroleitaliane#1]
Come da titolo, lo ha detto anche il nostro premier.

**Comment by napolux** [comment]
Il premier può dire quello che vuole.
[I dizionari che hanno voluto cavalcare l'onda mediatica](http://www.treccani.it/vocabolario/ricerca/petaloso/), anche.

Non presente in:
http://www.garzantilinguistica.it/ricerca/?q=petaloso
http://dizionari.repubblica.it/ (Hoepli)
