### ISSUE TITLE
Le parole non hanno apostrofi

### ISSUE THREAD

**Issue by vresetnikov** [napolux/paroleitaliane#10]
Salve,

Queste liste mancano degli apostrofi e accenti?

**Comment by napolux** [comment]
Non mi risulta https://github.com/napolux/paroleitaliane/blob/master/paroleitaliane/110000_parole_italiane_con_nomi_propri.txt#L1571

**Comment by vresetnikov** [comment]
> Non mi risulta https://github.com/napolux/paroleitaliane/blob/master/paroleitaliane/110000_parole_italiane_con_nomi_propri.txt#L1571

Probabilmente dipende da ogni file. Per esempio:

https://github.com/napolux/paroleitaliane/blob/master/paroleitaliane/lista_38000_cognomi.txt#L28498
